---
- name: "[MIDDLE] Install Java 1.8.0_92 on CentOS 6"
  yum:
#    name: awl-java16-jdk-jce-policy-std-1.6.0.45-1.awl6.x86_64,awl-java16-jdk-1.6.0.45-1.awl6.x86_64
    name: awl-java18-jdk-1.8.0.92-1.awl6.x86_64
    enablerepo: awl-main
    state: installed
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: "[MIDDLE] Install Java 1.8.0.131 on CentOS 7 server"
  yum:
    name: java-1.8.0-openjdk-1.8.0.131-11.b12.el7.x86_64
#    enablerepo: awl-main
    state: installed
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

#  - name: "[MIDDLE] Set /etc/alternatives/java to /usr/java/jdk-1.6/bin/java"
- name: "[MIDDLE] Set /etc/alternatives/java to /usr/java/jdk-1.8/bin/java"
  file:
    src: /usr/java/jdk-1.8/bin/java
    dest: /etc/alternatives/java
    state: link
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"


- name: "[MIDDLE : CENTOS 7] Set /etc/alternatives/java to /usr/java/jdk-1.6/bin/java"
  file:
    src: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-11.b12.el7.x86_64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"


