---
- name: "Push module configuration"
  copy:
    src: files/00_modules.conf
    dest: /etc/rsyslog.d/00_modules.conf
  notify: "Restart rsyslog"

- name: "Push global configuration"
  copy:
    src: files/20_global.conf
    dest: /etc/rsyslog.d/20_global.conf
  notify: "Restart rsyslog"

- name: "Push rsyslog server configuration"
  copy:
    src: files/60_server.conf
    dest: /etc/rsyslog.d/60_server.conf
  notify: "Restart rsyslog"

- name: "Ensure rsyslog is started"
  service:
    name: rsyslog
    state: started


- name: "Create /var/spool/rsyslog folder"
  file:
      path: "/var/spool/rsyslog"
      state: directory
      owner: root
      group: root

- name: "Setup Log rotation for concentrated files"
  copy:
    src: "files/archiver_logs.sh"
    dest: "/opt/archiver_logs.sh"
    owner: root
    group: root
    mode: 0744

- name: "Create /etc/cron.d/archiverlogs file"
  copy:
    content: "# File delivered by ANSIBLE\n# Archivage des logs centralises\n30 00 * * * root /opt/archiver_logs.sh > /dev/null 2>&1\n"
    dest: "/etc/cron.d/archiverlogs"
    force: no
    owner: root
    group: root
    mode: 0644

- name: "Enable ElasticSearch repository"
  yum_repository:
     name: "elasticsearch"
     description : Elastic repository for 6.x packages
     baseurl: https://artifacts.elastic.co/packages/6.x/yum
     gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
     gpgcheck: yes
     proxy: https://proxy-prod-scl.svc.meshcore.net:3128
     enabled: no
     state: present


- name: "Install filebeat to send log to Elastic stack"
  yum:
     name: filebeat-6.8.2-1.x86_64
     enablerepo: elasticsearch
     state: present

- name: "Push configuration"
  template:
     src: templates/filebeat.yml.j2
     dest: /etc/filebeat/filebeat.yml
     backup: yes
  notify:
    - restart filebeat

- name: "Ensure filebeat service is enabled and started"
  service:
    name: filebeat
    enabled: yes
    state: started

- name: "Test the remote logstash is available"
  wait_for:
    host: "{{ logstash_host }}"
    port: "{{ logstash_port }}"

