---
- hosts: EACC:IACC
  name: "Change network conf files"
  become: true
  tags: vlan_migration
  tasks:
  - name: "Change /etc/sysconfig/network-scripts/ifcfg-eth0"
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: '^IPADDR='
      line: 'IPADDR={{ ip_eth0 }}'
    notify: "Restart network service"
    tags: ipaddress

  - name: "Change /etc/sysconfig/network-scripts/ifcfg-eth0 for mask"
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: '^NETMASK='
      line: 'NETMASK=255.255.255.0'
    notify: "Restart network service"
    tags: mask

  - name: "Change /etc/sysconfig/network-scripts/ifcfg-eth0 for broadcast"
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: '^BROADCAST='
      line: 'BROADCAST={{ broadcast }}'
    notify: "Restart network service"
    tags: broadcast

  - name: "Deliver /etc/sysconfig/network-scripts/route-eth0"
    template:
      src: templates/route-eth0-front
      dest: "/etc/sysconfig/network-scripts/route-eth0"
      mode: 0644
      owner: root
      group: root
    tags: route
    notify: "Restart network service"

  - name: "Change /etc/sysconfig/network"
    lineinfile:
      path: /etc/sysconfig/network
      regexp: '^GATEWAY='
      line: 'GATEWAY={{ gw }}'
    tags: network
    notify: "Restart network service"

  - name: "Stop all services"
    command: "stop_service -a"
    tags: stop_service

  - name: "Edit /etc/host"
    lineinfile:
      path: "/etc/hosts"
      regexp: '.*{{ansible_hostname}}\.sys\.meshcore\.net$'
      line: '{{ ip_eth0 }} {{ansible_hostname}} {{ansible_hostname}}.sys.meshcore.net '
      backup: yes
    tags: etc_host

  handlers:
  - name: "Restart network service"
    service:
      name: network
      state: restarted
#    async: 10
#    poll: 5

